name: CI
on:
  push:
    branches:
    - main
    paths:
    - src/**
    - ui/**
    - pom.xml
    - .github/workflows/*
  pull_request:
    branches:
    - main
    paths:
    - src/**
    - ui/**
    - pom.xml
    - .github/workflows/*
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set VAULT_ADDR
      if: secrets.VAULT_ADDR != ''
      run:
        export VAULT_ADDR=${{ secrets.VAULT_ADDR }}
    - name: Import Secrets
      if: env.VAULT_ADDR != '' && (env.GITHUB_REF == 'refs/heads/develop' || env.GITHUB_REF == 'refs/heads/main')
      id: secrets
      uses: hashicorp/vault-action@v3.0.0
      with:
        exportToken: true
        exportEnv: true
        method: jwt
        url: ${{ env.VAULT_ADDR }}
        role: cicd
        secrets: |
          kv/data/cicd/sonatype username | SONATYPE_USERNAME ;
          kv/data/cicd/sonatype password | SONATYPE_PASSWORD ;
          kv/data/cicd/gpg secring | GPG_SECRING ;
          kv/data/cicd/gpg passphrase | GPG_PASSPHRASE ;
          kv/data/cicd/gpg passphrase | GPG_PASSPHRASE ;
          kv/data/cicd/maven settings-xml | MAVEN_SETTINGS_XML ;
    - name: Install GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        cache: 'maven'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Write settings.xml
      if: env.MAVEN_SETTINGS_XML != ''
      run: |
        mkdir -p ~/.m2
        cat <<EOF > ~/.m2/settings.xml
        ${MAVEN_SETTINGS_XML}
        EOF
    - name: Unit Tests
      run: ./mvnw -V --no-transfer-progress clean test
    - name: Executable Jar
      run: |
        set -ex
        apt-get -qq update -y && apt-get -qq install net-tools -y
        ./mvnw -V --no-transfer-progress package -DskipTests
        java -jar target/*.jar --server.port=8080 &
        .github/workflows/wait.sh
        curl --fail --show-error --silent http://localhost:8080/api/hello
        pkill -KILL java
